import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpRight,
  ArrowUpRightSquare,
  Bank,
  BarChart,
  Bell,
  Blockquote,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  BookmarkHeart,
  BookmarkPlus,
  BookmarkStar,
  BookmarkX,
  Box,
  Brush,
  Bullseye,
  Button,
  Calendar,
  CameraAlt,
  Cart,
  CartPlus,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  Clock,
  Code,
  CodeAlt,
  Cog,
  Copy,
  CreditCard,
  Cup,
  Cut,
  Dollar,
  DollarCircle,
  DotsHorizontalRounded,
  Dropbox,
  Envelope,
  EnvelopeOpen,
  Eye,
  File,
  FileCode,
  FileDetail,
  FilePlus,
  FileZip,
  Filter,
  Flag,
  FolderOpen,
  FolderPlus,
  FontFamily,
  Fullscreen,
  FullscreenExit,
  Gear,
  Gift,
  Globe,
  Grid,
  Hand,
  Happy,
  Heading1,
  Heading2,
  Heading3,
  Heart,
  Iframe,
  Image,
  InfoCircle,
  Italic,
  Key,
  KeyAlt,
  Layers,
  LightBulb,
  Link,
  Linkedin,
  ListOl,
  ListUl,
  Lock,
  MailOpen,
  Menu,
  MessageBubble,
  Microphone,
  Minus,
  Move,
  Music,
  MusicAlt,
  NetworkChart,
  NoteBook,
  Paperclip,
  PauseCircle,
  Pencil,
  Phone,
  Play,
  PlayCircle,
  Plus,
  Redo,
  RefreshCcw,
  Rename,
  Reply,
  RotateCcw10,
  RotateCw10,
  Save,
  Search,
  SearchMinus,
  SearchPlus,
  Send,
  Server,
  Share,
  Shield,
  ShoppingBag,
  Sparkle,
  Star,
  StarHalf,
  Store,
  Strikethrough,
  Stripe,
  Tag,
  Trash,
  Truck,
  Twitter,
  Underline,
  Undo,
  User,
  UserCircle,
  UserMinus,
  UserPlus,
  Video,
  VolumeLow,
  Waveform,
  X,
  XCircle,
  XSquare,
  type BoxIconProps,
} from "@boxicons/react";
import cx from "classnames";
import * as React from "react";

type IconPack = BoxIconProps["pack"];

const iconMap: Record<IconName, [React.ComponentType<BoxIconProps>, IconPack?]> = {
  // Archive
  archive: [Archive],
  "archive-fill": [Archive, "filled"],

  // Arrows
  "arrow-counterclockwise": [RotateCcw10],
  "arrow-diagonal-up-right": [ArrowUpRight],
  "arrow-down": [ArrowDown],
  "arrow-left": [ArrowLeft],
  "arrow-right": [ArrowRight],
  "arrow-right-circle": [ArrowRightCircle],
  "arrow-right-reply": [Reply],
  "arrow-up": [ArrowUp],
  "arrow-up-right-square": [ArrowUpRightSquare],
  "arrows-collapse": [FullscreenExit],
  "arrows-expand": [Fullscreen],

  // Finance / Commerce
  bank: [Bank],
  "bar-chart-fill": [BarChart, "filled"],
  "cart-plus": [CartPlus],
  "cart3-fill": [Cart, "filled"],
  "deal-fill": [Tag, "filled"],
  gift: [Gift],
  "gift-fill": [Gift, "filled"],
  "shop-window": [Store],
  "shop-window-fill": [Store, "filled"],
  stripe: [Stripe, "brands"],
  truck: [Truck],

  // Text formatting
  bold: [Bold],
  italic: [Italic],
  underline: [Underline],
  strikethrough: [Strikethrough],
  fonts: [FontFamily],
  h1: [Heading1],
  h2: [Heading2],
  h3: [Heading3],
  "ordered-list": [ListOl],
  "unordered-list": [ListUl],
  quote: [Blockquote],
  "quote-squared": [Blockquote, "filled"],
  "horizontal-rule": [Minus],
  code: [Code],
  "code-square": [CodeAlt],
  embed: [Iframe],
  undo: [Undo],
  redo: [Redo],

  // Books
  book: [Book],
  "book-half": [BookOpen],

  // Bookmarks
  "bookmark-check-fill": [BookmarkStar, "filled"],
  "bookmark-fill": [Bookmark, "filled"],
  "bookmark-heart-fill": [BookmarkHeart, "filled"],
  "bookmark-plus": [BookmarkPlus],
  "bookmark-x": [BookmarkX],

  // UI / Layout
  box: [Box],
  "box-arrow-in-right-fill": [ArrowRight, "filled"],
  brush: [Brush],
  bullseye: [Bullseye],
  button: [Button],
  grid: [Grid],
  "input-cursor-text": [Rename],
  sparkle: [Sparkle],
  stickies: [NoteBook],

  // Calendar / Time
  "calendar-all": [Calendar],
  "clock-history": [Clock],

  // Media
  "camera-video": [Video],
  "camera-video-fill": [Video, "filled"],
  camera2: [CameraAlt],
  media: [PlayCircle],
  image: [Image],
  "circle-pause": [PauseCircle],
  "circle-play": [PlayCircle],
  "music-note-beamed": [Music],
  soundwave: [Waveform],
  "volume-down": [VolumeLow],
  "mic-fill": [Microphone, "filled"],
  "skip-back-15": [RotateCcw10],
  "skip-forward-30": [RotateCw10],

  // Cards / Content
  card: [CreditCard],
  "card-image-fill": [Image, "filled"],
  "card-text": [FileDetail],

  // Status
  "check-square": [CheckSquare],
  circle: [Circle],
  "circle-fill": [Circle, "filled"],
  "info-circle": [InfoCircle],
  "info-circle-fill": [InfoCircle, "filled"],
  "shield-exclamation": [Shield],

  // Files
  download: [ArrowDown],
  "download-fill": [ArrowDown, "filled"],
  "upload-fill": [ArrowUp, "filled"],
  "file-arrow-down": [File],
  "file-earmark-binary-fill": [FileCode, "filled"],
  "file-earmark-diff": [File],
  "file-earmark-font": [FontFamily],
  "file-earmark-image-fill": [Image, "filled"],
  "file-earmark-medical": [FileDetail],
  "file-earmark-medical-fill": [FileDetail, "filled"],
  "file-earmark-music-fill": [MusicAlt, "filled"],
  "file-earmark-play-fill": [PlayCircle, "filled"],
  "file-earmark-plus": [FilePlus],
  "file-earmark-text": [FileDetail],
  "file-earmark-text-fill": [FileDetail, "filled"],
  "file-earmark-zip-fill": [FileZip, "filled"],
  "file-music": [MusicAlt],
  "file-play": [Play],
  "file-text": [FileDetail],
  "file-text-fill": [FileDetail, "filled"],
  "files-earmark": [File],

  // Folders
  "folder-plus": [FolderPlus],

  // Communication
  "chat-right-text-fill": [MessageBubble, "filled"],
  "emoji-smile": [Happy],
  "envelope-fill": [Envelope, "filled"],
  "envelope-open-fill": [EnvelopeOpen, "filled"],
  paperclip: [Paperclip],
  phone: [Phone],

  // Actions
  "eye-fill": [Eye, "filled"],
  filter: [Filter],
  link: [Link],
  pencil: [Pencil],
  plus: [Plus],
  save: [Save],
  scissors: [Cut],
  share: [Share],
  "three-dots": [DotsHorizontalRounded],
  trash2: [Trash],
  "zoom-in": [SearchPlus],
  "zoom-out": [SearchMinus],

  // Settings / Security
  gear: [Gear],
  "gear-fill": [Gear, "filled"],
  key2: [KeyAlt],
  "lock-fill": [Lock, "filled"],
  "lighting-fill": [LightBulb, "filled"],

  // People
  "people-fill": [User, "filled"],
  person: [User],
  "person-circle-fill": [UserCircle, "filled"],
  "person-plus-fill": [UserPlus, "filled"],
  "person-x-fill": [UserMinus, "filled"],

  // Misc
  cup2: [Cup],
  "diagram-2-fill": [NetworkChart, "filled"],
  dropbox: [Dropbox, "brands"],
  globe: [Globe],
  "half-star": [StarHalf],
  "hdd-network-fill": [Server, "filled"],
  "heart-fill": [Heart, "filled"],
  linkedin: [Linkedin, "brands"],
  "stack-fill": [Layers, "filled"],
  twitter: [Twitter, "brands"],

  // outline-* icons (basic pack)
  "outline-bell": [Bell],
  "outline-check": [Check],
  "outline-check-circle": [CheckCircle],
  "outline-check-circle-about": [CheckCircle],
  "outline-cheveron-double-left": [ChevronsLeft],
  "outline-cheveron-double-right": [ChevronsRight],
  "outline-cheveron-down": [ChevronDown],
  "outline-cheveron-left": [ChevronLeft],
  "outline-cheveron-right": [ChevronRight],
  "outline-cheveron-up": [ChevronUp],
  "outline-circle-play": [PlayCircle],
  "outline-clock": [Clock],
  "outline-credit-card": [CreditCard],
  "outline-currency-dollar": [Dollar],
  "outline-dots-circle-horizontal": [DotsHorizontalRounded],
  "outline-drag": [Move],
  "outline-drag-vert": [Move],
  "outline-duplicate": [Copy],
  "outline-key": [Key],
  "outline-mail-open": [MailOpen],
  "outline-menu": [Menu],
  "outline-refresh": [RefreshCcw],
  "outline-shopping-bag": [ShoppingBag],
  "outline-star": [Star],

  // solid-* icons (filled pack)
  "solid-bell": [Bell, "filled"],
  "solid-chat-alt": [MessageBubble, "filled"],
  "solid-check-circle": [CheckCircle, "filled"],
  "solid-cog": [Cog, "filled"],
  "solid-currency-dollar": [DollarCircle, "filled"],
  "solid-database": [Server, "filled"],
  "solid-document-text": [FileDetail, "filled"],
  "solid-flag": [Flag, "filled"],
  "solid-folder-open": [FolderOpen, "filled"],
  "solid-hand": [Hand, "filled"],
  "solid-key": [Key, "filled"],
  "solid-search": [Search, "filled"],
  "solid-send": [Send, "filled"],
  "solid-shield-exclamation": [Shield, "filled"],
  "solid-star": [Star, "filled"],
  "solid-user": [User, "filled"],

  // Close / Remove
  x: [X],
  "x-circle": [XCircle],
  "x-circle-fill": [XCircle, "filled"],
  "x-square": [XSquare],
};

type IconProps = {
  name: IconName;
} & React.JSX.IntrinsicElements["span"];
export const Icon = ({ name, className, ...props }: IconProps) => {
  const entry = iconMap[name];
  if (!entry) return <span className={cx("icon", `icon-${name}`, className)} {...props} />;
  const [Component, pack] = entry;
  return (
    <span className={cx("icon", className)} {...props}>
      <Component {...(pack ? { pack } : {})} />
    </span>
  );
};
