import type { ComponentType } from "react";

export type ArticleModule = {
  default: ComponentType;
  meta: { description: string };
};

const articleModules: Record<string, () => Promise<ArticleModule>> = {
  "10-dealing-with-vat": () => import("./articles/DealingWithVat"),
  "13-getting-paid": () => import("./articles/GettingPaid"),
  "15-1099s": () => import("./articles/Article1099s"),
  "20-how-do-i-contact-gumroad": () => import("./articles/HowDoIContactGumroad"),
  "37-how-to-delete-your-gumroad-account": () => import("./articles/HowToDeleteYourGumroadAccount"),
  "42-content-security": () => import("./articles/ContentSecurity"),
  "43-streaming-videos": () => import("./articles/StreamingVideos"),
  "44-build-gumroad-into-your-website": () => import("./articles/BuildGumroadIntoYourWebsite"),
  "46-what-currency-does-gumroad-use": () => import("./articles/WhatCurrencyDoesGumroadUse"),
  "47-how-to-refund-a-customer": () => import("./articles/HowToRefundACustomer"),
  "51-what-is-gumroads-refund-policy": () => import("./articles/WhatIsGumroadsRefundPolicy"),
  "53-what-browsers-does-gumroad-support": () => import("./articles/WhatBrowsersDoesGumroadSupport"),
  "54-not-receiving-updates": () => import("./articles/NotReceivingUpdates"),
  "60-adding-a-cover-image": () => import("./articles/AddingACoverImage"),
  "62-testing-a-purchase": () => import("./articles/TestingAPurchase"),
  "64-is-gumroad-for-me": () => import("./articles/IsGumroadForMe"),
  "66-gumroads-fees": () => import("./articles/GumroadsFees"),
  "67-the-settings-menu": () => import("./articles/TheSettingsMenu"),
  "70-can-i-sell-services": () => import("./articles/CanISellServices"),
  "74-the-analytics-dashboard": () => import("./articles/TheAnalyticsDashboard"),
  "76-license-keys": () => import("./articles/LicenseKeys"),
  "78-my-customer-did-not-receive-a-receipt": () => import("./articles/MyCustomerDidNotReceiveAReceipt"),
  "79-gumroad-discover": () => import("./articles/GumroadDiscover"),
  "81-custom-product-urls": () => import("./articles/CustomProductUrls"),
  "82-membership-products": () => import("./articles/MembershipProducts"),
  "101-designing-your-product-page": () => import("./articles/DesigningYourProductPage"),
  "107-common-zapier-integrations-with-gumroad": () => import("./articles/CommonZapierIntegrationsWithGumroad"),
  "110-gumroads-subprocessors": () => import("./articles/GumroadsSubprocessors"),
  "112-mobile-friendly-files": () => import("./articles/MobileFriendlyFiles"),
  "120-protecting-your-privacy-on-gumroad": () => import("./articles/ProtectingYourPrivacyOnGumroad"),
  "121-sales-tax-on-gumroad": () => import("./articles/SalesTaxOnGumroad"),
  "124-your-gumroad-profile-page": () => import("./articles/YourGumroadProfilePage"),
  "125-how-to-compress-a-video-using-handbrake": () => import("./articles/HowToCompressAVideoUsingHandbrake"),
  "126-setting-up-versions-on-a-digital-product": () => import("./articles/SettingUpVersionsOnADigitalProduct"),
  "128-discount-codes": () => import("./articles/DiscountCodes"),
  "130-pdf-stamping": () => import("./articles/PdfStamping"),
  "131-using-workflows-to-send-automated-updates": () => import("./articles/UsingWorkflowsToSendAutomatedUpdates"),
  "133-pay-what-you-want-pricing": () => import("./articles/PayWhatYouWantPricing"),
  "134-how-does-gumroad-handle-chargebacks": () => import("./articles/HowDoesGumroadHandleChargebacks"),
  "136-find-your-products-url": () => import("./articles/FindYourProductsUrl"),
  "139-how-to-cancel-your-customers-subscriptions": () => import("./articles/HowToCancelYourCustomersSubscriptions"),
  "144-send-customers-directly-to-your-payment-form": () => import("./articles/SendCustomersDirectlyToYourPaymentForm"),
  "149-adding-a-product": () => import("./articles/AddingAProduct"),
  "153-setting-up-a-custom-domain": () => import("./articles/SettingUpACustomDomain"),
  "155-things-you-cant-sell-on-gumroad": () => import("./articles/ThingsYouCantSellOnGumroad"),
  "156-gumroad-and-adult-content": () => import("./articles/GumroadAndAdultContent"),
  "160-suspension": () => import("./articles/Suspension"),
  "161-what-gumroad-considers-fraud": () => import("./articles/WhatGumroadConsidersFraud"),
  "169-how-to-send-an-update": () => import("./articles/HowToSendAnUpdate"),
  "170-audience": () => import("./articles/Audience"),
  "174-third-party-analytics": () => import("./articles/ThirdPartyAnalytics"),
  "176-metadata-for-audio-files": () => import("./articles/MetadataForAudioFiles"),
  "177-the-gumroad-dashboard-app": () => import("./articles/TheGumroadDashboardApp"),
  "189-safe-gumroad-buying": () => import("./articles/SafeGumroadBuying"),
  "190-how-do-i-get-a-refund": () => import("./articles/HowDoIGetARefund"),
  "191-a-guide-to-buying-on-gumroad": () => import("./articles/AGuideToBuyingOnGumroad"),
  "192-how-do-i-cancel-my-membership": () => import("./articles/HowDoICancelMyMembership"),
  "193-my-purchase-isnt-downloading": () => import("./articles/MyPurchaseIsntDownloading"),
  "194-i-need-an-invoice": () => import("./articles/INeedAnInvoice"),
  "195-theres-an-issue-with-my-purchase": () => import("./articles/TheresAnIssueWithMyPurchase"),
  "196-contact-gumroad": () => import("./articles/ContactGumroad"),
  "197-why-do-i-have-a-1-charge-from-gumroad": () => import("./articles/WhyDoIHaveA1ChargeFromGumroad"),
  "198-your-gumroad-library": () => import("./articles/YourGumroadLibrary"),
  "199-how-do-i-access-my-purchase": () => import("./articles/HowDoIAccessMyPurchase"),
  "200-i-need-a-vat-refund": () => import("./articles/INeedAVatRefund"),
  "203-why-did-my-payment-fail": () => import("./articles/WhyDidMyPaymentFail"),
  "204-get-to-know-your-gumroad-receipt": () => import("./articles/GetToKnowYourGumroadReceipt"),
  "206-how-to-open-zip-and-rar-files": () => import("./articles/HowToOpenZipAndRarFiles"),
  "208-how-do-i-send-my-gumroad-purchase-to-my-kindle": () =>
    import("./articles/HowDoISendMyGumroadPurchaseToMyKindle"),
  "209-how-do-i-combine-two-accounts": () => import("./articles/HowDoICombineTwoAccounts"),
  "210-send-your-purchase-to-dropbox": () => import("./articles/SendYourPurchaseToDropbox"),
  "211-im-not-receiving-updates": () => import("./articles/ImNotReceivingUpdates"),
  "212-i-never-received-a-receipt": () => import("./articles/INeverReceivedAReceipt"),
  "213-how-do-i-give-a-product-as-a-gift": () => import("./articles/HowDoIGiveAProductAsAGift"),
  "214-why-was-i-charged-by-gumroad": () => import("./articles/WhyWasIChargedByGumroad"),
  "215-when-will-my-purchase-be-shipped": () => import("./articles/WhenWillMyPurchaseBeShipped"),
  "216-delete-credit-card-information": () => import("./articles/DeleteCreditCardInformation"),
  "217-i-have-extra-charges-from-gumroad-after-my-purchase": () =>
    import("./articles/IHaveExtraChargesFromGumroadAfterMyPurchase"),
  "222-product-ratings-on-gumroad": () => import("./articles/ProductRatingsOnGumroad"),
  "223-payoneer-and-gumroad": () => import("./articles/PayoneerAndGumroad"),
  "247-what-your-customers-see": () => import("./articles/WhatYourCustomersSee"),
  "248-delete-a-product": () => import("./articles/DeleteAProduct"),
  "249-affiliate-faq": () => import("./articles/AffiliateFaq"),
  "251-incorrect-recurring-charge": () => import("./articles/IncorrectRecurringCharge"),
  "252-multiple-accounts": () => import("./articles/MultipleAccounts"),
  "260-your-payout-settings-page": () => import("./articles/YourPayoutSettingsPage"),
  "266-why-are-my-customers-purchases-failing": () => import("./articles/WhyAreMyCustomersPurchasesFailing"),
  "268-customer-dashboard": () => import("./articles/CustomerDashboard"),
  "269-balance-page": () => import("./articles/BalancePage"),
  "270-url-parameters": () => import("./articles/UrlParameters"),
  "275-paypal-connect": () => import("./articles/PaypalConnect"),
  "278-guide-to-memberships": () => import("./articles/GuideToMemberships"),
  "280-create-application-api": () => import("./articles/CreateApplicationApi"),
  "281-payout-delays": () => import("./articles/PayoutDelays"),
  "282-how-do-purchases-work-for-my-customers": () => import("./articles/HowDoPurchasesWorkForMyCustomers"),
  "283-fraudulent-purchases": () => import("./articles/FraudulentPurchases"),
  "285-turning-off-third-party-trackers": () => import("./articles/TurningOffThirdPartyTrackers"),
  "286-how-do-i-report-a-gumroad-creator": () => import("./articles/HowDoIReportAGumroadCreator"),
  "288-dmca-counter-notices": () => import("./articles/DmcaCounterNotices"),
  "289-file-size-limits-on-gumroad": () => import("./articles/FileSizeLimitsOnGumroad"),
  "290-facebook-domain-verification": () => import("./articles/FacebookDomainVerification"),
  "292-account-login-security": () => import("./articles/AccountLoginSecurity"),
  "295-external-integration": () => import("./articles/ExternalIntegration"),
  "304-products-dashboard": () => import("./articles/ProductsDashboard"),
  "324-accessibiility-statement": () => import("./articles/AccessibiilityStatement"),
  "325-indirect-taxes-on-sales-via-discover": () => import("./articles/IndirectTaxesOnSalesViaDiscover"),
  "326-teams-and-roles": () => import("./articles/TeamsAndRoles"),
  "327-purchasing-power-parity": () => import("./articles/PurchasingPowerParity"),
  "329-customer-moderation": () => import("./articles/CustomerModeration"),
  "330-stripe-connect": () => import("./articles/StripeConnect"),
  "331-creating-upsells": () => import("./articles/CreatingUpsells"),
  "333-affiliates-on-gumroad": () => import("./articles/AffiliatesOnGumroad"),
  "334-more-like-this": () => import("./articles/MoreLikeThis"),
  "335-custom-refund-policy": () => import("./articles/CustomRefundPolicy"),
  "336-singaporean-gst": () => import("./articles/SingaporeanGst"),
  "339-product-bundles": () => import("./articles/ProductBundles"),
  "341-collaborations": () => import("./articles/Collaborations"),
  "343-wishlists": () => import("./articles/Wishlists"),
  "344-rate-and-review-your-purchase": () => import("./articles/RateAndReviewYourPurchase"),
  "345-tipping": () => import("./articles/Tipping"),
  "346-installment-plans": () => import("./articles/InstallmentPlans"),
  "347-gumroad-community": () => import("./articles/GumroadCommunity"),
};

export async function getArticle(slug: string): Promise<ArticleModule | null> {
  const loader = articleModules[slug];
  if (!loader) return null;
  return loader();
}
